export default {
  User: {
    SignIn: "/api/signIn",
    SignUp: "/api/signUp",
    GetUser: "/api/getUser",
    GetAllUsers: "/api/getAllUsers",
    ToggleFollower: "/api/toggleFollower",
    GetFollowers: "/api/getFollowers",
    GetFollowing: "/api/getFollowing",
    SearchUsers: "/api/search/users",
    EditProfile: "/api/editProfile",
    ChangePassword: "/api/changePassword",
  },
  Post: {
    CreatePost: "/api/createPost",
    GetUserPosts: "/api/getUserPosts",
    GetFollowingPosts: "/api/getFollowingPosts",
    GetPost: "/api/getPost",
    GetAllPosts: "/api/getAllPosts",
    DeletePost: "/api/deletePost",
    SupportPost: "/api/supportPost",
    OpposePost: "/api/opposePost",
    SearchPosts: "/api/search/posts",
  },
};
