version: "3"
services:
  react-app-prod:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    stdin_open: true
    ports:
      - "5000:80"
    networks:
      - mern-app
    depends_on:
      - api-server-prod
    tty: true
    links:
      - api-server

  api-server-prod:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    networks:
      - mern-app
    env_file:
      - .env

networks:
  mern-app:
    driver: bridge
