version: "3"
services:
  react-app:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
    volumes:
      - ./client/src:/app/src
      - ./server/routers/routes.js:/app/routes.js
    depends_on:
      - api-server
    tty: true
    links:
      - api-server
  api-server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    networks:
      - mern-app
    env_file:
      - .env
    volumes:
      - ./server:/app
      - /app/node_modules/

networks:
  mern-app:
    driver: bridge
