//AUTH
export const userConstants = {
  SIGN_IN: "SIGN_IN",
  SIGN_OUT: "SIGN_OUT",
  CREATE_ACCOUNT: "CREATE_ACCOUNT",
  SET_USER: "SET_USER",
  GET_PROFILE: "GET_PROFILE",
  SET_LOADING: "SET_LOADING",
};

export const notificationConstants = {
  SHOW_NOTIFICATION: "SHOW_NOTIFICATION",
  REMOVE_NOTIFICATION: "REMOVE_NOTIFICATION",
};
