//AUTH
export const userConstants = {
  SIGN_IN: "SIGN_IN",
  SIGN_OUT: "SIGN_OUT",
  CREATE_ACCOUNT: "CREATE_ACCOUNT",
  SET_USER: "SET_USER",
  GET_PROFILE: "GET_PROFILE",
  REMOVE_PROFILE: "REMOVE_PROFILE",
  SET_LOADING: "SET_LOADING",
  UPDATE_USER: "UPDATE_USER",
};

export const postsConstants = {
  GET_FEED: "GET_FEED",
  GET_USER_POSTS: "GET_USER_POSTS",
};

export const pageConstants = {
  SHOW_NOTIFICATION: "SHOW_NOTIFICATION",
  REMOVE_NOTIFICATION: "REMOVE_NOTIFICATION",
  ADD_SIDE_PAGE: "ADD_SIDE_PAGE",
  REMOVE_SIDE_PAGE: "REMOVE_SIDE_PAGE",
};
